from __future__ import annotations

import argparse
from pathlib import Path

from src.step2.langgraph_step2 import run_step2


DEFAULT_INPUT_JSON = Path(
    "outputs/streamlit_runs/20260214_184136/outputs/input_layer_output.json"
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Step 2: deterministic preprocessing + strict-schema fact extraction (writes facts JSON)"
    )
    parser.add_argument(
        "--input-json",
        required=False,
        default=str(DEFAULT_INPUT_JSON),
        help=(
            "Path to input_layer_output.json generated by Step 1. "
            f"(default: {DEFAULT_INPUT_JSON.as_posix()})"
        ),
    )
    parser.add_argument(
        "--out",
        default="outputs/step2",
        help="Output directory for chunks + facts JSON",
    )
    parser.add_argument(
        "--preprocess-only",
        action="store_true",
        help="Only write inspection_chunks.json and thermal_chunks.json (skip LLM extraction)",
    )
    args = parser.parse_args()

    input_path = Path(args.input_json)
    if not input_path.exists():
        raise SystemExit(
            "Input JSON not found: "
            + str(input_path)
            + "\nTip: pass --input-json to a valid Step 1 output, e.g. "
            + "outputs/streamlit_runs/<timestamp>/outputs/input_layer_output.json"
        )

    run_step2(
        input_json_path=str(input_path),
        out_dir=str(Path(args.out)),
        run_llm=(not args.preprocess_only),
    )
    print(str(Path(args.out).resolve()))


if __name__ == "__main__":
    main()
